CREATE DATABASE doingsdone
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE UTF8_GENERAL_CI;

USE doingsdone;

CREATE TABLE projects (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name CHAR(255) NOT NULL,
  user_id INT(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE tasks (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name CHAR(50) NOT NULL,
  datetime_add DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status TINYINT(4) NOT NULL DEFAULT 0,
  deadline DATE NULL DEFAULT NULL,
  user_id INT(11) NOT NULL,
  project_id INT(11) NOT NULL,
  file VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE users (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email CHAR(45) NOT NULL UNIQUE,
  password CHAR(255) NOT NULL,
  name CHAR(255) DEFAULT NULL,
  datetime_add DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB CHARSET=utf8;

CREATE INDEX project ON projects(name);
CREATE INDEX deadline ON tasks(deadline);
CREATE INDEX task ON tasks(name);
CREATE FULLTEXT INDEX task_ft_search ON tasks(name);
